
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jul 18 23:47:41 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 35;
  public static final int CHAR = 46;
  public static final int CONST = 6;
  public static final int NAMESPACE = 17;
  public static final int NOT_EQUAL = 31;
  public static final int LPAREN = 20;
  public static final int CONTINUE = 14;
  public static final int FOR = 15;
  public static final int MINUS = 25;
  public static final int STATIC = 16;
  public static final int RPAREN = 21;
  public static final int SEMICOLON = 40;
  public static final int AND = 36;
  public static final int LT = 34;
  public static final int OR = 37;
  public static final int BOOL = 45;
  public static final int COMMA = 42;
  public static final int CLASS = 4;
  public static final int INC = 38;
  public static final int DIV = 27;
  public static final int PLUS = 24;
  public static final int IF = 7;
  public static final int DOT = 43;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int EQUAL = 29;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 26;
  public static final int DOUBLE_EQUAL = 30;
  public static final int NUMBER = 44;
  public static final int MOD = 28;
  public static final int IDENT = 47;
  public static final int BREAK = 3;
  public static final int VOID = 12;
  public static final int GTE = 33;
  public static final int LBRACK = 22;
  public static final int COLON = 41;
  public static final int LBRACE = 18;
  public static final int ELSE = 5;
  public static final int READ = 10;
  public static final int RBRACK = 23;
  public static final int RBRACE = 19;
  public static final int EXTENDS = 13;
  public static final int DEC = 39;
  public static final int GT = 32;
  public static final int PRINT = 9;
}

